/*
 * Master configuration header, to keep all top level configuration options.
 */
/* DO NOT EDIT THIS FILE, EDIT USER_CONFIG.H INSTEAD */

#ifndef CONFIG_H_
#define CONFIG_H_

#define CONFIG_BOARD_ADC (0)
#define CONFIG_BOARD_PWM (1)

#include "user_config.h"


/* UDP port to listen for broadcasts on */
#ifndef CONFIG_BCAST_PORT
#define CONFIG_BCAST_PORT 			(4950)	
#endif

/* No of attempts to try and get address by DHCP before giving up
 * ipv4LL will be used upon failure
 */
#ifndef CONFIG_DHCP_TRIES
#define CONFIG_DHCP_TRIES 			(10)	
#endif 


/***** SET OPTIONS BASED ON BOARD TYPE *****/

/* Verify board type */
#ifndef CONFIG_BOARD
#error "BOARD must be set"
#endif

/*** ADC board type ***/
#if CONFIG_BOARD == CONFIG_BOARD_ADC

/* Set Hardware Features */
#define CONFIG_ADC_SUPPORT 			(1)
#define CONFIG_TRIGGER_SUPPORT 		(1)
#define CONFIG_PWM_SUPPORT			(0)

/* Board captures data */
#define CONFIG_CAPTURE_SUPPORT		(1)

/* Set board string for network protocol*/
#define CONFIG_BOARD_TYPE_STRING	"ADC"

/* Set default display */
#ifndef CONFIG_7SEG_DEFAULT
#define CONFIG_7SEG_DEFAULT			"0000"
#endif

/*** PWM board type ***/
#elif CONFIG_BOARD == CONFIG_BOARD_PWM

/* Set Hardware Features */
#define CONFIG_ADC_SUPPORT 			(0)
#define CONFIG_TRIGGER_SUPPORT 		(0)
#define CONFIG_PWM_SUPPORT 			(1)

/* Board does not capture data */
#define CONFIG_CAPTURE_SUPPORT		(0)

/* Set board string for network protocol */
#define CONFIG_BOARD_TYPE_STRING	"PWM"

/* Set default display */
#ifndef CONFIG_7SEG_DEFAULT
#define CONFIG_7SEG_DEFAULT			"1111"
#endif

/*** Unknown board type ***/
#else
#error "Unknown value for CONFIG_BOARD"
#endif

#endif /* CONFIG_H_ */
